---
- name: Enable DNS services
  command: "/snap/bin/microk8s enable dns:{{ dns_server }}"

- name: Enable metallb services
  command: "/snap/bin/microk8s enable metallb:{{ lb_range }}"

- name: Enable metrics-server services
  command: "/snap/bin/microk8s enable metrics-server"

- name: Enable prometheus services
  command: "/snap/bin/microk8s enable prometheus"